def exc(m,s,e,li=-1):
    m = list(m)
    m[s],m[e] = m[e],m[s]
    if t == 0 and abs(s-e) not in [1,5]:
        r = [e,12,s]
    else:
        r = [e,s] if li == -1 else li
    info = [r,10 if m[s] == 'a' else int(m[s])]
    return [''.join(m),info]
def aro(p):
    li = [7,11,13,17] if t == 0 else []
    li1 = [i for i in li if i != p] if p in li else []
    dxy = [-sx,1,sx,-1]
    li = ([(0,1,2,3,4),(4,9,14,19,24),(20,21,22,23,24),(0,5,10,15,20)] if t == 0 else 
          [(0,1,2,3),(3,7,11,15),(12,13,14,15),(0,4,8,12)])
    return li1+[p + dxy[i] for i in range(4) if p not in li[i]]
def exp(n,m,p=-1,tf=''):
    res = []
    for i in range(size) if n > 0 else [p]:
        if (n > 0 and m[i] != '0') or fx[i]:
            continue
        for j in [j for j in aro(i) if m[j] not in ['x','0x'][n > 0]+tf and not fx[j]]:
            res.append(exc(m,i,j) if n > 0 else [j,j])
    return res
def src(n,m,*a,res1=-1,tf=''):
    global res
    if n == -2:
        s, = a
        li = []
    if n in [-1,-3]:
        s, = a
    if n == 0:
        s,e = a
    if n == 1:
        p,pk = a
    q = [m if n > 0 else s] 
    mkd,step = {q[0]:-1},{q[0]:-1}
    while 1:
        if n == -2 and not q:
            return li
        if n == -1 and (len(q) > 1 or not q):
            break
        if n == 0 and not q:
            return -1
        cur = q.pop(0)
        if n == -3 and m[cur] != '0':
            break
        if n == 0 and cur == e:
            break
        if n == 1:
            if (pk == -1 and cur == p) or (p != -1 and cur[p] == pk):
                break
        for i,j in exp(n,cur if n > 0 else m,cur,tf):
            if i not in mkd:
                if n == -2:
                    li.append(i)
                q.append(i)
                mkd[i],step[i] = cur,j
    mkd[-2] = cur
    path = [step[cur]]
    while mkd[cur] != -1:
        cur = mkd[cur]
        path.append(step[cur])
    if n > 0:
        res1 = res1 if res1 != -1 else res
        res1 += path[::-1][1:]
        return mkd[-2]
    return path[::-1][1:]
def sort(m,e,pk):
    global res
    if m[e] == pk:
        fx[e]=1
        return m
    def move1(m,p):
        li = []
        m1 = m[:]
        m1 = src(1,m,p,'0',res1=li,tf=pk)
        m1 = src(1,m1,p,pk,res1=li)
        ct = len([i for i in [e]+src(-2,m1,e,tf=pk) if m1[i] == '0'])
        return ct,m1,li
    def move2(m,li):
        global res
        li1 = []
        for i in li:
            fx[i]=1
            li1.append((i,src(-2,m,e)))
            fx[i]=0
        li = max(li1,key=lambda i:len(i[1]))
        for i in src(0,m,s,li[0]):
            ct,m1,res1 = move1(m,i)
            res += res1
            m = m1[:]
        return m
    r = src(-1,m,e)
    ctz = m.count('0')-(3 if t == 0 else 0)
    while m[e] != pk:        
        s = m.index(pk)
        cs = src(0,m,s,e)[0]
        ct = len([i for i in [e]+src(-2,m,e,tf=pk) if m[i] == '0'])         # need fix
        if ct < 2 and not (cs == e and m[e] == '0'):
            m = move2(m,[i for i,j in exp(0,m,s) if i != e])
            continue
        ct,m1,res1 = move1(m,cs)
        if ct < 2 and not (cs == e and m[e] == '0') and not (cs == e and ct > -1):
            m = move2(m,[s]+[i for i,j in exp(0,m,cs) if i != s])
            s = m.index(pk)
            r1 = src(0,m,s,e)[:ctz]
            for i in r1[::-1]:
                m = src(1,m,i,'0',tf=pk)
                fx[i]=1
            fxli(r1,0)
            for i in r1:
                m = src(1,m,i,pk)
            continue
        res += res1
        m = m1[:]
    fx[e]=1
    return m
def main(g_t,m,*a):
    global t,sy,sx,size,fx,fxli,res
    t = g_t
    sy,sx = [5,5] if t == 0 else [4,4]
    size = sy * sx
    fx = {i:0 for i in range(size)}
    fxli = lambda li,n: fx.update({i:n for i in li})
    res = []
    if t == 0:
        leaf = '1x0x23000450006700089x0xa'
        fx[2],fx[12]=1,1
        li = [0,4,20,24,5,10,15,9,14,19]
        for i in li:
            m = sort(m,i,leaf[i])
    if t == 1:
        leaf = '1234567800000000'
        li = [0,1,2,3]+([7,6,5,4] if m[10]=='x' else [4,5,6,7])
        for i in li:
            m = sort(m,i,leaf[i])
    if t == 2:
        m1 = m[:]
        m2,leaf1 = a
        leaf2 = ''.join([leaf1[i] for i in [3,2,1,0,7,6,5,4,11,10,9,8,15,14,13,12]])
        for m,leaf in [[m1,leaf1],[m2,leaf2]]:
            leaf = list(leaf)
            li = [12,13,14,15,8] if m.index('x') in [5,6] else [0,1,2,3,4]
            li1 = []
            for i in li:
                pk = leaf[i]
                if leaf[i] == '0':
                    r = src(-3,''.join(leaf),i)
                    p = r[-1]
                    pk = leaf[p]
                m = sort(m,i,pk)
                if leaf[i] == '0':
                    leaf[p],leaf[i] = '0',pk
                    li1.append([i]+r)
            fx={i:0 for i in fx}
            res += li1[::-1] + ['!']
    return res

from time import time       # temp
tl = lambda *n:tp_log(' '.join(map(str,n)))
drl_report_line(0)
set_tool('tool wei')
set_velx(1500); set_accx(2500)
set_velj([100,150,180,225,225,225]); set_accj(400)
begin_blend(10)
ml,mj,aml,amj = movel,movej,amovel,amovej
def up(p,mod=0,h=-1):
    p,h = p[:],h if h != -1 else 260
    p[2] = p[2] + h if mod else h
    return p
tool = 0
def cht(t=0.6,n = -1):
    global tool,pos
    tool = (1 - tool)
    amj([0,0,0,0,0,-180 if tool else 180],a=1500,t=t,mod=1)
    pos = poss[tool][T]
isgrip = 0
def grip(n):
    global isgrip
    isgrip = n
    if tool:
        if not n:
            wait(0.1)
        wt(40,n,b=0)
        wait(0.15)
    else:
        set_tool_digital_outputs([1,-2] if n else [-1,2])
        wait(0.25)

ser=serial_open("COM")
def ts(ad,m=[],y=0,x=0,b=1):
    if b:
        ad += 100 * (1 + T)
    k='00'+['W','R'][bool(y)]+'SB06%DW'
    k=[ord(i) for i in k]
    n=len(m) if not y else y*x
    ad = [0]*(3-len(str(ad))) + list(map(int,str(ad)))
    k+=[ord(str(abs(i))) for i in ad]
    k+=[ord(i) for i in '{:02X}'.format(n)]
    if not y:
        for i in m:
            if i<0:
                i+=2**16
            k+=[ord(j) for j in '{:04X}'.format(i)]
    ser.write([5]+k+[4])
    wait(0.02 if n is 1 else 0.05)
    k=ser.read(ser.inWaiting())
    if y:
        for i in range(0,y*x*4,4):
            v=int(k[10+i:14+i],16)
            if v&(1<<15):
                v-=2**16 
            m.append(v)
        return m if len(m) > 1 else m[0]
def wt(*a,b = 1):
    if isinstance(a[0],int):
        a = [a]
    for i,j in a:
        ts(i,j if isinstance(j,list) else [j],b=b)
def rd(ad,y=1,x=1):
    return ts(ad,[],y,x)

def wt_init():
    global T
    for T in range(3):
        li = [[2, 19, 20, 19, 10, 7, 0, 0, 0, 8, 9, 0, 20, 0, 4, 6, 0, 0, 0, 1, 5, 19, 20, 19, 3],
              [0, 0, 0, 0, 0, 5, 0, 8, 0, 7, 9, 1, 6, 3, 4, 2],
              [0, 0, 0, 0, 0, 9, 0, 0, 0, 0, 0, 5, 1, 2, 3, 4, 1, 0, 3, 0, 0, 9, 0, 4, 0, 2, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 4, 2, 9, 5, 1, 3, 0, 0, 0, 0, 0, 0]][T]
        wt(0,li)
wt_init()       # temp

def rd1(ad,y,x):
    di = {10:'a',19:'x',20:'0'} if not T else {9:'x'}
    return ''.join([di[i] if i in di else str(i) for i in rd(ad,y,x)])
root,leaf = [-1]*3,[-1]*3
for T in range(3):
    y,x = [5,5] if not T else [4,4]
    root[T] = rd1(0,y,x)
    if T == 2:
        root[T] = [rd1(16,y,x),rd1(32,y,x)]
        leaf[T] = rd1(0,y,x)

def ps(pos,y,x,sy=40,sx=40):
    s = y * x
    pos = [pos] * s
    for i in range(1,s):
        pos[i] = trans(pos[i-1],[-sx,0,0,0,0,0]) if i % x else trans(pos[i-x],[0,sy,0,0,0,0])
    return pos
elcA = ps(posx(427.57, 297.78, 226.11, 179.86, -90, -90),5,5)
elcB = ps(posx(157.91, 337.81, 224.38, 0.03, 90, 90),4,4)
elcC = [ps(posx(-44.88, 343.72, 225.76, 179.85, 90.01, 89.96),4,4),ps(posx(-264.78, 344.8, 225.07, 179.83, 90, 90),4,4)]
airA = None         # ps(None,5,5)
airB = None         # ps(None,4,4)
airC = None         # [ps(None,4,4),ps(None,4,4)]
poss = [[elcA,elcB,elcC],[airA,airB,airC]]

def mt1(p,g,d=[],mod=0,h=-1,z=0,b1=1,b2=0,a1=2500,a2=1500):
    tp = trans(pos[p],[0,0,-z,0,0,0])
    ml(up(tp,mod,h),a=a1)
    if b2:
        return
    ml(tp,a=a2,r=5)
    if not g:
        aml([0,0,z=-0.15,0,0,0],mod=1,acc=300)
    grip(g)
    if d:
        ad,val=d
        wt(ad,val)
    if b1:
        ml(up(tp))

# 3. Main
def Run():  
    global pos      # T == 2
    if T == 2:
        exit(tl(pos))
    for i in range(len(res)):
        li,pk = res[i]
        b = T == 0 and len(li) != 2
        if b:
            s,p,e = li
        else:
            s,e = li            
        a = res[i+1][1] if i < len(res)-1 else -1
        b = res[i-1][1] if i else -1
        if pk != b:
            mt1(s,1,[s,0],b1=0)
            aml([0,0,3,0,0,0],a=500,mod=1)
        if b:
            mt1(p,1,mod=1,h=3,b2=1,a2=500)
        mt1(e,0,[e,pk],mod=1,h=3,b2=pk==a,a2=500)
        
# Todo
# fix, 'perf2'
# 다트 파일 / vscode 파일 비교
# 과제 파일 / 규격 파일 비교

wt(30,1,b=False)
import time         # temp
time_start = time.time()        # temp

ress = []
for i in range(3):
    if i == 2:
        r1,r2 = root[i]
        ress.append(main(i,r1,r2,leaf[i]))
    else:
        ress.append(main(i,root[i]))
    tl(i,'done !!!')        # temp
        
for i in range(3):
    grip(0)
    if i == 0:
        mj([90,0,90,90,-90,0])
        tool = 0
    if i == 2:
        aml([0,0,100,0,0,0],mod = 1)
        mj([90,0,90,90,90,0])
    T,pos,res = i,poss[tool][i],ress[i]
    Run()
    
wt(30,1,b=False)
time_end = time.time() - time_start         # temp
minute,second = int(time_end // 60),int(time_end % 60)         # temp
tl('{}m {}s\n'.format(minute,second))         # temp