
from queue import PriorityQueue
from collections import deque

def exc1(m,s,e,r):
    m = list(m)
    m[s],m[e] = m[e],m[s]
    info = [r,int(m[s])]
    return [''.join(m),info]

def exc2(m,n,p,pk):      # 변형 : 그리퍼 2개 사용
    m = list(m)
    m[p] = '0' if n else pk
    info = [n,p,int(pk)]
    return [''.join(m),info]

def aro(pos):
    if pos in cache:
        return cache[pos]
    res = []
    dy,dx = [-1,0,1,0],[0,1,0,-1]
    y,x = divmod(pos,sx)
    for i in range(4):
        ny,nx = y + dy[i],x + dx[i]
        if -1 < ny < sy and -1 < nx < sx:
            res.append(ny * sx + nx)
    cache[pos] = res
    return res

def exp(n,m,p=-1):
    res = []
    if t==1 and Ct==0:      # 변형 : 그리퍼 2개 사용
        for i in range(si):
            if ((m[i] in Pk1 and all([i in m for i in Pk1])) or (m[i] in Pk2 and all([i in m for i in Pk2]))) and m[i] not in '0x':
                res.append(exc2(m,1,i,m[i]))
            if m[i] == '0':
                for pk in Pk1+Pk2:
                    if pk not in m:
                        res.append(exc2(m,0,i,pk))
        return res
    di1,di2 = {},{}
    for i in range(si):
        if not fx[i] and m[i] != 'x':
            if n < 1 or m[i] != '0':
                di1[i] = i
            if n < 1 or m[i] == '0':
                di2[i] = i
    for i in di1 if n > 0 else [p]:
        q = deque([i])
        r = {i:[di1[i]]}
        while q:
            cur = q.popleft()
            for j in range(si) if t == 1 else aro(cur):
                if j in r or j not in di2:
                    continue
                if n > 0:
                    q.append(j)
                r[j] = r[cur] + [di2[j]]
                if t == 0 and n > 0 and j in hli:       # hole
                    continue
                res.append(exc1(m,di2[j],di1[i],r[j]) if n > 0 else [j,j])
    return res

visited = 0
def src(n,m,*a):
    global res
    global visited       # temp
    if n < 1:
        s,e = a
        if n == 0 and (n,s,e) in cache:
            return cache[n,s,e]
    if n == 1:
        leaf,p,pk = a
    if n == 2:
        leaf, =a
    cur = m if n > 0 else s
    q = PriorityQueue() if n > 0 else deque([])
    mkd = {cur:[cur]}
    g = {cur:0}    
    def heu1(m):
        ct = 0
        if p != -1:
            rp = len([i for i in src(0,m,m.index(pk),p) if m[i] not in '0'+pk])
            ct += 10000 * rp
            r2 = src(-1,m,p,-1)
            if len(r2) > 1:
                for i in range(len(r2)):
                    if m[r2[::-1][i]] not in '0'+pk:
                        ct += 100 * (1+i)
            if not rp:
                ct = -2 ** (30 if m[p] == pk else 20)
        else:
            for i in range(si):
                if not fx[i] and m[i] not in '0x':                
                    ct += len(src(0,m,i,p if p!=-1 else leaf.index(m[i])))
        return ct
    def heu2(m):
        ct = 0
        li = [0,1,2,3,4,5,6,7]
        for pk in [i for i in leaf if i != '0']:
            if pk in m:
                for i in range(1,8):
                    if m[li[(m.index(pk)+i)%8]] == leaf[li[(leaf.index(pk)+i)%8]] != '0':
                        ct -= 100    
        return ct
    put = lambda cur: q.put((g[cur] + (heu2 if n == 2 else heu1)(cur), cur)) if n > 0 else q.append(cur)
    get = lambda : q.get()[1] if n > 0 else q.popleft()
    put(cur)
    while 1:
        if n == -1 and len(q) > 1:      # default
            break
        cur = get()
        if n > 0:      # temp
            visited += 1
        if n == -2 and m[cur] != '0' and cur not in e:
            break
        if n == 0 and cur == e:
            break
        if n == 1:
            if (p == -1 and cur == leaf) or (p != -1 and cur[p] == pk):
                break
        if n == 2:
            ct = 8 - Ct
            H = -100 * ((ct-1)*ct)
            if heu2(cur) == H:
                break
        for i,j in exp(n,cur if n > 0 else m,cur):
            if i not in mkd:
                mkd[i] = mkd[cur] + [j]
                g[i] = g[cur] + 1
                put(i)
    res1 = mkd[cur]
    if n > 0:
        res += res1[1:]
        return cur
    if n == 0:
        cache[n,s,e] = res1
    return res1

def main(g_t,m,*a):
    global t,sy,sx,si,fx,fxli,cache,res
    t = g_t
    sy,sx = [[3,4],[1,8]][t]
    si = sy * sx
    fx = {i:0 for i in range(si)}
    fxli = lambda li,n: fx.update({i:n for i in li})
    cache = {}
    res = []
    if t == 0:
        global hli      # hole
        leaf = a[0]
        hli = a[1] if len(a)==2 else []      # hole
        seq = [0,1,2,3,4,5]
        xli = [i for i in range(12) if m[i] == 'x']
        if xli:
            seq = [[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],
                   [0,8,1,5,9],[4,8,0],[7,3,11],[3,11,2,6,10],
                   [8,9,10,11,4],[8,9,10,11,4],[8,9,10,11,4],[8,9,10,11,4]][xli[0]]
        seq = [i for i in seq if i not in xli + hli]              # hole
        hd,hdr = [],{}
        leaf1 = list(leaf[:])
        for i in seq:
            pk = leaf1[i]
            if pk == '0':
                r = src(-2,leaf1,i,hd)
                pk = leaf1[r[-1]]
                hd.append(i)
                hdr[i] = r
                leaf1[r[-1]],leaf1[i] = '0',pk
            m = src(1,m,''.join(leaf1),i,pk)
            fx[i] = 1
        m = src(1,m,''.join(leaf1),-1,-1)
        for i in hd[::-1]:
            res.append([hdr[i],int(m[i])])
    if t == 1:
        global Ct,Pk1,Pk2
        leaf,=a
        Ct = leaf.count('0')        # 빈 칸 개수
        St = sorted([i for i in '12345678' if i in leaf],key=int)
        Pk1,Pk2 = St[:-4],St[-4:]       # 사각팩, 원형팩
        src(2,m,leaf)
    return res   
 
def ts(ad,val=[],y=1,x=1):
    ser = serial_open(port='COM')
    li = list('00RSB06%DW'+'%03d'%ad)
    li += [i for i in '{:02X}'.format(y*x)]
    if val != []:
        li[2] = 'W'
        li += '%04X'%(val&0xFFFF)
    ser.write([5]+[ord(i) for i in li]+[4])
    wait(0.05 if val == [] else 0.02) 
    if val == []:
        li = ser.read(ser.inWaiting()).decode()
        val = [int(li[10+i:14+i],16) for i in range(0,y*x*4,4)]
    serial_close(ser)
    return val[0] if type(val) != int and len(val) == 1 else val

tl = lambda *n:tp_log(' '.join(map(str,n)))
drl_report_line(0)
set_tool('tool')
set_velx(1500); set_accx(2500); set_velj([150,150,180,225,225,225]); set_accj(400)
begin_blend(25)
ml,mj,aml,amj,mjx = movel,movej,amovel,amovej,movejx
H = 370
def up(p,mod=0,h=-1):
    p,h = p[:],h if h != -1 else H
    p[2] = p[2]+h if mod else h
    return p
tool = 0
def cht(n=-1,t=0.6):
    global tool
    if n == tool:
        return 0
    tool = 1 - tool
    amj([0,0,0,0,0,180 if tool else -180],a=1500,mod=1)
    wait(t)
    return 0.6
isgrip = 0
def grip(n):
    global isgrip
    isgrip = n
    if tool:
        if not n:
            wait(0.1)
        ts(40,n)
    else:
        set_tool_digital_outputs([1,-2] if n else [-1,2])
    wait(0.25)
itli = [0,1,2,3,4,5,6,7]
def it(n,t=0.6,mod=0):
    global itli
    if not mod:
        n = 4 - itli.index(n)
    ts(10,n)
    wait(t * abs(n))
    itli = itli[-n:] + itli[:-n]
    return 0.6 * abs(n)
gp = -1
def gt(n):
    global gp
    di = {(-1,2):5,(2,1):5,(2,4):10,(1,4):10,(4,3):5,(3,2):10}
    ts(21,di[gp,n])
    ts(20,n)
    gp = n
    
#def ps(p,y,x):
    #pos = {}
    #sy = [(p[1][i] - p[0][i]) / (y-1) if y != 1 else 0 for i in range(6)]
    #sx = [(p[2][i] - p[0][i]) / (x-1) if x != 1 else 0 for i in range(6)]
    #for i in range(y*x):
        #pos[i] = [p[0][j]+(sy[j] * (i//x))+(sx[j] * (i%x)) for j in range(6)]
    #return pos  
#elcA = ps([posx(-285.59, 223.52, 227.96, 0.47, -90.02, -89.96),posx(-285.33, 304.86, 228.68, 0.49, -90.04, -89.96),posx(-405.93, 223.53, 228.46, 0.92, -90, -89.99)],3,4)
#airA = ps([posx(-285.85, 221, 135.67+60, 1.28, -90, 90),posx(-285.45, 302.03, 135.63+60, 1.42, -90.02, 90.03),posx(-406.06, 221.52, 135.86+60, 1.9, -90.03, 90.03)],3,4)
    
def ps(p,y,x,sy=40,sx=40):
    pos = {}
    for i in range(y*x):
        err = 1 if i>7 else 0
        pos[i] = trans(p,[-sx * (i%x),sy * (i//x) + err,0,0,0,0])
    return pos
elcA = ps(posx(-285.23, 225.34, 229.17, 0.39, -90.01, -89.98),3,4)
airA = ps(posx(-285.78, 225.63, 135.7+60, 1.67, -90.03, 90.05),3,4)
#elcA = ps(posx(-284.88, 385.62, 231.26, 0.26, -90.02, -89.96),3,4)
#airA = ps(posx(-285.59, 384.86, 136.16+60, 0.32, -90.02, 89.99),3,4)
A = {i:[elcA[i],airA[i],100+i] for i in range(12)}
IT = {0:[None,None,5]}
GTI = {0:[None,[0]*6,500],1:[[0]*6,None,501]}
GTO = {0:[None,[0]*6,500],1:[[0]*6,None,501]}

def mt1(pos,n,p,pk,b=0):
    z = -1.5 if not n and not tool else 0
    tp = trans(pos[p][tool],[0,0,z,0,0,0])
    mh = [[0,-1],[0,-1]] if b else [[1,5],[0,-1]]
    a = [2000,2000] if b else [300,1000] if tool else [800,2500]
    if n==1:
        mh,a = mh[::-1],a[::-1]
    if b:
        mjx(up(tp,*mh[0]),sol=2 if pos in [GTO,A] else 3)
    else:
        ml(up(tp,*mh[0]),a=2100,r=25 if n==2 else 1)
    if n < 2:
        if z:
            set_tool_digital_outputs([-1,-2])
            wait(0.1)
        ml(tp,a=a[0],r=5)
        grip(n)
        ts(pos[p][2],0 if n else pk)
        ts([600,601][tool],pk if n else 0)
        ml(up(tp,*mh[1]),a=a[1])
        
def Run(pos,res):
    for [r,pk] in res:
        n = len(r)
        li = [r[1]-r[0]]
        cht(pk > 3)
        mt1(pos,1,r[0],pk)
        for i in range(1,n):
            if i < n-1:
                dire = r[i+1] - r[i]
                skip = li[i-1] == dire
                li.append(dire)
                if skip:
                    continue
            mt1(pos,1 if not i else 0 if i == n-1 else 2,r[i],pk)

def RunIT(pos,res):
    #for [r,pk] in res:
        #for i in range(2):
    for [n,p,pk] in res:
        t1 = it(p,0)
        t2 = cht(pk > 3,0)        
        wait(t1 if t1 > t2 else t2)
        mt1(IT,n,0,pk,1)
    it(4 - [ts(i) for i in range(1,9)].index(int(leaf[1][4])),mod=1)
    wait(0.3)

def wt_init():
    for i in range(2):
        li = [[0,0,0,2,5,9,7,10,4,1,6,3,3,7,2,0,0,9,4,10,6,1,5,0],
              [1,5,6,9,3,7,4,2]][i]
        for ad,val in enumerate(li):
            ts([100,200][i]+ad,val)            
    for ad,val in enumerate([4,6,5,9,1,2,7,3]):
        ts(1+ad,val)    
    # default
    #for i in range(2):
        #li = [[0,1,0,3,5,0,4,0,2,7,0,6,1,2,3,4,5,6,7,0,0,0,0,0],
              #[5,4,3,2,1,0,7,6]][i]
        #for ad,val in enumerate(li):
            #ts([100,200][i]+ad,val)            
    #for ad,val in enumerate([5,1,2,0,6,7,4,3]):
        #ts(1+ad,val)
    ts(500,0)
    ts(501,0)
    ts(600,0)
    ts(601,0)
wt_init()       # temp

#ts(30,1)        # buzz

import time         # temp
time_start = time.time()        # temp

def cvt(li):
    di = {9:'x',10:'0'}
    return ''.join([di[i] if i in di else str(i) for i in li])
root,leaf,info = [-1]*2,[-1]*2,[-1]*2
li = ts(100,[],4,3)
info[0] = [i for i in range(12) if li[i] == 10]
root[0] = cvt(li)
leaf[0] = cvt(ts(112,[],4,3))
root[1] = cvt(ts(1,[],1,8))
leaf[1] = cvt(ts(200,[],1,8))

ress = [-1]*2
#ress[0] = main(0,root[0],leaf[0],info[0]); tl('0 done!!!')
#ress[1] = main(1,root[1],leaf[1]); tl('1 done!!!')
ress = [
[[[4, 0, 1, 2], 5], [[8, 4, 0, 1], 4], [[9, 8, 4, 0], 1], [[10, 9, 8, 4], 6], [[11, 10, 9, 8], 3], [[3, 7, 11, 10, 9], 2], [[2, 3, 7, 11, 10], 5], [[1, 2, 3, 7, 11], 4], [[0, 1, 2, 3], 1], [[4, 0, 1, 2], 6], [[8, 4], 3], [[9, 8], 2], [[10, 9], 5], [[6, 10], 7], [[2, 6], 6], [[3, 2], 1], [[11, 7, 3], 4], [[10, 11], 7], [[9, 10], 5], [[8, 9], 2], [[2, 1], 1], [[3, 2], 4], [[11, 7, 3], 7], [[10, 11], 5], [[9, 10], 2], [[1, 0], 1], [[2, 1], 4], [[3, 2], 7], [[11, 7, 3], 5], [[10, 11], 2], [[6, 10, 9, 8], 6], [[2, 6, 10], 7], [[1, 2, 6], 4], [[0, 1], 1], [[6, 2], 4], [[10, 6], 7], [[11, 10], 2], [[3, 7, 11], 5], [[2, 3], 4], [[1, 2], 1], [[10, 9], 2], [[11, 10], 5], [[3, 7, 11], 4], [[2, 3], 1], [[6, 2, 1, 0], 7], [[11, 7, 6, 2], 4], [[10, 11], 5], [[9, 10, 6], 2], [[11, 10], 5], [[3, 7, 11], 1], [[6, 7, 3], 2], [[10, 6], 5], [[11, 10, 9], 1], [[6, 10], 5], [[2, 6], 4], [[3, 2], 2], [[0, 1], 7], [[4, 0], 3]],
[[1, 0, 4], [1, 4, 1], [0, 4, 4], [0, 0, 1], [1, 1, 6], [1, 7, 3], [0, 7, 6], [0, 1, 3], [1, 4, 4], [1, 5, 2], [0, 4, 2], [1, 0, 1], [0, 5, 1], [1, 4, 2], [0, 0, 2], [1, 1, 3], [0, 4, 3], [1, 5, 1], [0, 1, 1], [0, 5, 4], [1, 7, 6], [1, 4, 3], [0, 4, 6], [1, 5, 4], [0, 7, 4], [0, 5, 3], [1, 1, 1], [1, 2, 5], [0, 1, 5], [1, 4, 6], [0, 2, 6], [1, 1, 5], [0, 1, 1], [1, 5, 3], [0, 4, 3], [1, 1, 1], [0, 1, 5], [1, 6, 7], [0, 5, 7], [0, 6, 1], [1, 0, 2], [1, 7, 4], [0, 7, 2], [1, 6, 1], [0, 6, 4], [0, 0, 1]]]

grip(0)
#mj([90,0,90,90,-90,0])
#mjx(up(IT[0][0]),sol=3)
#RunIT(IT,ress[1])
#am = ts(100,[],3,4)
#seq = [[4,1],[5,2],[6,3],[7,-1]]
#for i in range(len(seq)):
    #pk1,pk2 = seq[i]
    #itli = [0,1,2,3,4,5,6,7]
    #itm = ts(1,[],1,8)
    #b = pk2!=-1
    #H = 370
    #if not i:
        #gt(2)         # inB2
        #it(itm.index(pk1))
    #cht(1)
    #mt1(IT,1,0,pk1,1)
    #if b:
        #it(itm.index(pk2),0)
    #mt1(GTI,0,1,pk1,1)
   #
    #if b:
        #gt(1)         # inB1
        #cht(0,0.1)
        #mt1(IT,1,0,pk2,1)
        #if i<len(seq)-1:
            #it(itm.index(seq[i+1][0]),0)
        #mt1(GTI,0,0,pk2,1)
    #H = 300
    #gt(4)            # outB2
    #cht(1,0)
    #amj([0,0,0,0,180,-30],a=800,mod=1)
    #if i==3:
        #wait(0.5)
    #mt1(GTO,1,1,pk1,1)
    #if b:
        #gt(3)            # outB1
        #cht(0)
        #mt1(GTO,1,0,pk2,1)
        #gt(2)         # inB2
        #mt1(A,0,am.index(pk2),pk2,1)
        #cht(1,0.8)
    #mt1(A,0,am.index(pk1),pk1,1)
    #if i<len(seq)-1:
        #amj([90,0,90,90,-90,180],a=600)
        #wait(0.3)

mj([90,0,90,90,90,0])          # TEMP        
H = 270
Run(A,ress[0])

#ts(30,1)        # buzz

time_end = time.time() - time_start         # temp
minute,second = int(time_end // 60),int(time_end % 60)         # temp
tl('{}m {}s\n'.format(minute,second))         # temp